# Generated by Django 5.2.17 on 2026-08-13 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sfs_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('company_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'st_companies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('code_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='code_user', to='sfs_core.allusers', to_field='user_id')),
            ],
            options={
                'db_table': 'st_code',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('type', models.CharField(default='beginner', max_length=30)),
                ('is_paid', models.BooleanField(default=0)),
                ('price', models.FloatField(default=0)),
                ('course_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='courses_user_id', to='sfs_core.allusers', to_field='user_id')),
            ],
            options={
                'db_table': 'st_course_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_categories_user', to='sfs_core.allusers', to_field='user_id')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_categories_course', to='skiltrix_core.courses', to_field='course_id')),
            ],
            options={
                'db_table': 'course_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('course_name', models.TextField()),
                ('college_name', models.TextField()),
                ('education_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='education_user', to='sfs_core.allusers', to_field='user_id')),
            ],
            options={
                'db_table': 'st_education',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('internship_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='internship_company', to='skiltrix_core.companies', to_field='company_id')),
            ],
            options={
                'db_table': 'st_internship',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('rating_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to='skiltrix_core.courses', to_field='course_id')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_user', to='sfs_core.allusers', to_field='user_id')),
            ],
            options={
                'db_table': 'st_ratings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resume_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='resumes_user', to='sfs_core.allusers', to_field='user_id')),
            ],
            options={
                'db_table': 'st_resumes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('skill_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='skills_user', to='sfs_core.allusers', to_field='user_id')),
            ],
            options={
                'db_table': 'st_skills',
                'managed': True,
            },
        ),
    ]
