# Generated by Django 5.2.17 on 2026-08-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfs_core', '0001_initial'),
        ('skiltrix_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='language_user', to='sfs_core.allusers', to_field='user_id')),
            ],
            options={
                'db_table': 'languages',
                'managed': True,
            },
        ),
    ]
