# Generated by Django 5.2.17 on 2026-08-17 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix_core', '0002_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table='st_courses',
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=105)),
                ('description', models.TextField()),
                ('video', models.CharField(max_length=55)),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='courses_video_id', to='skiltrix_core.courses', to_field='course_id')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='courses_videos_user_id', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'db_table': 'st_course_videos',
                'managed': True,
            },
        ),
    ]
