# Generated by Django 5.2.17 on 2026-08-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix_core', '0003_alter_courses_table_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='image',
            field=models.CharField(default='image.webp', max_length=50),
        ),
    ]
