# Generated by Django 5.2.17 on 2026-08-26 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix_core', '0004_videos_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='apply_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='deadline',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='internship',
            name='is_paid',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='internship',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='internship',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='share',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship_company', to='skiltrix_core.companies', to_field='company_id'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment_user_id', to=settings.AUTH_USER_MODEL, to_field='user_id')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment_video_id', to='skiltrix_core.videos', to_field='video_id')),
            ],
            options={
                'db_table': 'st_comments',
                'managed': True,
            },
        ),
    ]
