# Generated by Django 5.2.17 on 2026-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix_core', '0005_internship_apply_link_internship_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
