# Generated by Django 5.2.17 on 2026-08-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix_core', '0006_videos_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='type',
            field=models.CharField(default='remote', max_length=12),
        ),
        migrations.AlterField(
            model_name='videos',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='share',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
