# Generated by Django 5.2.17 on 2026-08-31 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix_core', '0007_internship_type_alter_videos_like_alter_videos_share_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes_user', to=settings.AUTH_USER_MODEL, to_field='user_id')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes_video', to='skiltrix_core.videos', to_field='video_id')),
            ],
            options={
                'db_table': 'st_likes',
                'managed': True,
            },
        ),
    ]
