# Generated by Django 5.2.15 on 2026-06-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activity_id', models.CharField(max_length=50, unique=True)),
                ('platform', models.CharField(max_length=10)),
                ('platform_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AllErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(max_length=50)),
                ('error_msg', models.TextField()),
                ('user_id', models.CharField(max_length=40)),
                ('ip', models.CharField(max_length=50)),
                ('activity', models.TextField()),
                ('version', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'allerrors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HackathonPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hackathon_payments',
            },
        ),
        migrations.CreateModel(
            name='HackathonProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hackathon_projects',
            },
        ),
        migrations.CreateModel(
            name='HackathonTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('type', models.CharField(default='member', max_length=20)),
                ('team_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'hackathon_teams',
            },
        ),
        migrations.CreateModel(
            name='HackathonUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='user', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hackathon_users',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='Created', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('activity_id', models.CharField(max_length=50)),
                ('total_id', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=15)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'total_activity',
                'managed': True,
            },
        ),
    ]
