# Generated by Django 5.2.17 on 2026-10-02 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(max_length=50)),
                ('error_msg', models.TextField()),
                ('error_code', models.IntegerField(default=200)),
                ('ip', models.CharField(max_length=50)),
                ('activity', models.TextField()),
                ('platform', models.CharField(default='app', max_length=10)),
                ('platform_name', models.CharField(default='sfs_blueprints', max_length=50)),
                ('version', models.CharField(max_length=15)),
                ('status', models.CharField(default='active', max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_user', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'db_table': 'allerrors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeviceFCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.TextField()),
                ('platform', models.CharField(max_length=10)),
                ('platform_name', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_user', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'db_table': 'devices_fcm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TotalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('activity_id', models.CharField(max_length=50)),
                ('total_id', models.CharField(max_length=50)),
                ('platform', models.CharField(default='app', max_length=10)),
                ('platform_name', models.CharField(default='sfs_blueprints', max_length=50)),
                ('version', models.CharField(max_length=15)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_user', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'db_table': 'total_activity',
                'managed': True,
            },
        ),
    ]
