# Generated by Django 5.2.15 on 2026-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allerrors',
            name='platform',
            field=models.CharField(default='app', max_length=10),
        ),
        migrations.AddField(
            model_name='allerrors',
            name='platform_name',
            field=models.CharField(default='sfs_blueprints', max_length=50),
        ),
        migrations.AddField(
            model_name='totalactivity',
            name='platform',
            field=models.CharField(default='app', max_length=10),
        ),
        migrations.AddField(
            model_name='totalactivity',
            name='platform_name',
            field=models.CharField(default='sfs_blueprints', max_length=50),
        ),
    ]
