# Generated by Django 5.2.15 on 2026-08-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_lib', '0003_allusers_bp_bpcat_bpcategories_bpdlv_bpimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hackathon_payments',
            },
        ),
        migrations.CreateModel(
            name='HackathonProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hackathon_projects',
            },
        ),
        migrations.CreateModel(
            name='HackathonTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('type', models.CharField(default='member', max_length=20)),
                ('team_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'hackathon_teams',
            },
        ),
        migrations.CreateModel(
            name='HackathonUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='user', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hackathon_users',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='Created', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bpcat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bpcategories',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='bpimages',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='bpcategories',
            name='category',
        ),
        migrations.DeleteModel(
            name='BpDlv',
        ),
        migrations.DeleteModel(
            name='AllUsers',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='BP',
        ),
        migrations.DeleteModel(
            name='BPImages',
        ),
        migrations.DeleteModel(
            name='BpCat',
        ),
        migrations.DeleteModel(
            name='BPCategories',
        ),
    ]
