# Generated by Django 5.2.17 on 2026-09-09 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('station_name', models.CharField(max_length=255)),
                ('station_code', models.CharField(max_length=10, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('station_category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=100, unique=True)),
                ('train_name', models.CharField(max_length=255)),
                ('source_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('train_number', models.CharField(max_length=20, unique=True)),
                ('day', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'trains',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='train_core.trains')),
            ],
            options={
                'db_table': 'train_days',
                'managed': True,
            },
        ),
    ]
