# Generated by Django 5.2.17 on 2026-09-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='frequency',
            field=models.CharField(default='Daily', max_length=50),
        ),
        migrations.AddField(
            model_name='trains',
            name='own',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('ALL', 'All Days')], max_length=3)),
                ('schedule_id', models.CharField(max_length=100, unique=True)),
                ('train', models.ForeignKey(db_column='train_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='train_core.trains', to_field='train_id')),
            ],
            options={
                'db_table': 'train_schedules',
                'managed': True,
            },
        ),
    ]
