# Generated by Django 5.2.15 on 2026-06-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=35)),
                ('profile', models.CharField(max_length=50)),
                ('user_type', models.CharField(default='user', max_length=5)),
                ('platform', models.CharField(max_length=10)),
                ('platform_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'all_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BpDlv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('bp_pla_id', models.CharField(max_length=35)),
                ('download_type', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('dlv_id', models.CharField(max_length=50, unique=True)),
                ('platform', models.CharField(max_length=10)),
                ('platform_name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=15)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sfs_bp_dlv',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('fviews', models.IntegerField(default=0)),
                ('flikes', models.IntegerField(default=0)),
                ('fdownloads', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('fshare', models.IntegerField(default=0)),
                ('zipfiles', models.CharField(max_length=50)),
                ('sfs_link', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('bp_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=12)),
                ('ip', models.CharField(max_length=50)),
                ('feature', models.BooleanField(default=0)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bp_user', to='sfs_core.allusers', to_field='user_id')),
            ],
            options={
                'db_table': 'sfs_bp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BpCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_category', models.CharField(max_length=20)),
                ('bp_name', models.CharField(max_length=35)),
                ('bp_img', models.CharField(max_length=40)),
                ('bp_para', models.TextField()),
                ('category_id', models.CharField(max_length=25, unique=True)),
                ('status', models.CharField(max_length=11)),
                ('ip', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bp_cat_user', to='sfs_core.allusers', to_field='user_id')),
            ],
            options={
                'db_table': 'sfs_bp_cat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BPCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=11)),
                ('ip', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('bp', models.ForeignKey(db_column='bp_id', on_delete=django.db.models.deletion.CASCADE, related_name='bp_category_bp', to='sfs_core.bp', to_field='bp_id')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='bp_categories', to='sfs_core.bpcat', to_field='category_id')),
            ],
            options={
                'db_table': 'sfs_bp_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BPImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('bp', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bp_user_image', to='sfs_core.bp', to_field='bp_id')),
            ],
            options={
                'db_table': 'sfs_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('status', models.CharField(max_length=15)),
                ('time', models.DateTimeField()),
                ('bp', models.ForeignKey(db_column='bp_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments_bp', to='sfs_core.bp', to_field='bp_id')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to='sfs_core.allusers', to_field='user_id')),
            ],
            options={
                'db_table': 'sfs_comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('bp', models.ForeignKey(db_column='bp_id', on_delete=django.db.models.deletion.CASCADE, related_name='bp_favorites_bp', to='sfs_core.bp', to_field='bp_id')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bp_favorites_user', to='sfs_core.allusers', to_field='user_id')),
            ],
            options={
                'db_table': 'sfs_favorites',
                'managed': True,
            },
        ),
    ]
