# Generated by Django 5.2.17 on 2026-09-04 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfs_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpimages',
            name='bp',
            field=models.ForeignKey(db_column='bp_id', on_delete=django.db.models.deletion.CASCADE, related_name='bp_user_image', to='sfs_core.bp', to_field='bp_id'),
        ),
    ]
