# Generated by Django 5.2.15 on 2026-07-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfs_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
