# Generated by Django 5.2.15 on 2026-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfs_core', '0003_alter_allusers_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allusers',
            old_name='time',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='allusers',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='profile',
            field=models.CharField(default='profile.webp', max_length=50),
        ),
    ]
