# Generated by Django 5.2.15 on 2026-07-26 13:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfs_core', '0004_rename_time_allusers_created_at_alter_allusers_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='allusers',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='allusers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
