# Generated by Django 5.2.15 on 2026-07-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfs_core', '0005_alter_allusers_managers_allusers_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='status',
            field=models.CharField(default='approved', max_length=20),
        ),
    ]
