# Generated by Django 5.2.15 on 2026-08-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfs_core', '0006_alter_allusers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
