# Generated by Django 5.2.15 on 2026-08-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfs_core', '0007_allusers_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='profile',
            field=models.CharField(default='profile.webp', max_length=500),
        ),
    ]
