# Generated by Django 5.2.17 on 2026-08-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activity_id', models.CharField(max_length=50, unique=True)),
                ('platform', models.CharField(max_length=10)),
                ('platform_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AllErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(max_length=50)),
                ('error_msg', models.TextField()),
                ('error_code', models.IntegerField(default=200)),
                ('user_id', models.CharField(max_length=40)),
                ('ip', models.CharField(max_length=50)),
                ('activity', models.TextField()),
                ('platform', models.CharField(default='app', max_length=10)),
                ('platform_name', models.CharField(default='sfs_blueprints', max_length=50)),
                ('version', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'allerrors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TotalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('activity_id', models.CharField(max_length=50)),
                ('total_id', models.CharField(max_length=50)),
                ('platform', models.CharField(default='app', max_length=10)),
                ('platform_name', models.CharField(default='sfs_blueprints', max_length=50)),
                ('version', models.CharField(max_length=15)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'total_activity',
                'managed': True,
            },
        ),
    ]
