# Generated by Django 5.2.17 on 2026-08-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allerrors',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='totalactivity',
            name='user_id',
        ),
        migrations.AddField(
            model_name='allerrors',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_user', to=settings.AUTH_USER_MODEL, to_field='user_id'),
        ),
        migrations.AddField(
            model_name='totalactivity',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_user', to=settings.AUTH_USER_MODEL, to_field='user_id'),
        ),
        migrations.CreateModel(
            name='DeviceFCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.TextField()),
                ('platform', models.CharField(max_length=10)),
                ('platform_name', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_user', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'db_table': 'devices_fcm',
                'managed': True,
            },
        ),
    ]
