# Generated by Django 5.2.17 on 2026-08-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_remove_allerrors_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AlterField(
            model_name='allerrors',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicefcm',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
